version: '3.3'
volumes:
  data:
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - /home/deivid/Arquivos/alura/react/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=admin
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
